name: build-and-deploy-function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy template
        run: |
          az group create --location uksouth --name rg-scoped-logging-demo
          az deployment group create --resource-group rg-scoped-logging-demo --template-file $GITHUB_WORKSPACE/Infrastructure/template.bicep --parameters appName=scopedloggingdemo
    
  deploy-functionapp:
    needs: [deploy-infrastructure]
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --output ./output --no-restore

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'scopedloggingdemo'
        package: './output'

    - name: deploy template
      run: |
        az functionapp config appsettings set --resource-group rg-scoped-logging-demo --name scopedloggingdemo --settings "FUNCTIONS_EXTENSION_VERSION=~4"