name: CI


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: delete resource group
        run: |
          az group delete --name rg-scoped-logging-demo
